### PR TITLE
Add `bundle report-issue`

### PR DESCRIPTION
**Pull request by colby-swandale**
This is a copy of @indirect's proposal from [bundler/bunder#4925](https://github.com/bundler/bundler/issues/4925)

### CODE REVIEW

**Comment by hmistry** [comment]
[Nice rendered view of above RFC](https://github.com/colby-swandale/rfcs/blob/786dc30d9479fb9c7b13ea45250c26d0a535f95f/text/0002-bundler-report-issue.md)

**Comment by hmistry** [comment]
I really like the overall concept. There's a lot of info collected. A couple of knee-jerk reactions are:
1. Since we know the type of error, can we only collect what's necessary? In other words, don't collect anything that's not remotely needed at all.
2. I presume there can be privacy and security concerns of the user. For example: the user paths in the shell can give out more clues about a github user, i.e. a different internet username. For companies, this can be a potential leak of their entire stack for outsiders to see - thinking of Gemfile.lock.
3. Will there be an interface for a user to preview and edit/approve before submission? As a user, I want this control.

**Comment by colby-swandale** [comment]
Quick thought: Don't use Gists, unlike issues, gists can be deleted by the user as well when the user deletes their account.

**Comment by indirect** [comment]
Final comment period starts here! Please give us your feedback by July 7.

**Pull request closed without merging**
